DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id REFERENCES users(id) ON DELETE CASCADE
  specialization_id REFERENCES specializations(id) ON DELETE CASCADE
 );
